# Generated by Django 5.0.3 on 2024-03-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_register_delete_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Company',
        ),
    ]
