# Generated by Django 5.0.3 on 2024-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_rename_person_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='aadress',
            new_name='address',
        ),
    ]
