# Generated by Django 5.0.3 on 2024-03-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_alter_person_age_alter_person_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Company',
        ),
    ]
